name: kegi_sudo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #fluttertoast: ^8.0.9
  bloc: ^7.0.0-nullsafety.0
  flutter_bloc: ^7.0.1
  rxdart: ^0.26.0
  country_code_picker: ^2.0.2
  #shimmer: ^2.0.0
  #cached_network_image: ^3.0.0
  dio: ^4.0.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.9
  sizer: ^2.0.15
  provider: ^6.0.1
  #image_picker: ^0.8.4+4
  #path_provider: ^2.0.8
  otp_text_field: ^1.1.2
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.1.2
  location: ^4.3.0
  geocode: ^1.0.1
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  custom_info_window: ^1.0.1
  get: ^4.6.1
  image_picker: ^0.8.4+11
  flutter_google_places: ^0.3.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  material_segmented_control: ^3.1.2
  date_time_picker: ^2.1.0
  http: ^0.13.4
  xml: ^5.0.0
  device_info_plus: ^3.0.1
  webview_flutter: ^3.0.2
  flutter_dialogs: ^2.1.1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1
  substring_highlight: ^1.0.24
  scrollable_positioned_list: ^0.2.2
  flutter_svg: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppins_bold
      fonts:
        - asset: assets/fonts/poppins_bold.ttf

    - family: Helvetica_Neue_medium1
      fonts:
        - asset: assets/fonts/Helvetica_Neue_medium1.ttf

    - family: poppins_regular
      fonts:
        - asset: assets/fonts/poppins_regular.ttf

    - family: avenir_roman
      fonts:
        - asset: assets/fonts/avenir_roman.ttf

    - family: avenir_heavy
      fonts:
        - asset: assets/fonts/avenir_heavy.ttf

    - family: montserrat_bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: montserrat_medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: montserrat_regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: montserrat_thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf

    - family: montserrat_light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: gotham_black
      fonts:
        - asset: assets/fonts/Gotham-Black.otf

    - family: gotham_thin
      fonts:
        - asset: assets/fonts/Gotham-Thin.otf

    - family: gotham_xlight
      fonts:
        - asset: assets/fonts/Gotham-XLight.otf

    - family: gotham_bold
      fonts:
        - asset: assets/fonts/Gotham-Bold.otf

    - family: gotham_light
      fonts:
        - asset: assets/fonts/GothamLight.ttf

    - family: gotham_medium
      fonts:
        - asset: assets/fonts/GothamMedium.ttf

    - family: quicksand_medium
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf

    - family: quicksand_regular
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf

    - family: quicksand_semibold
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
