import 'package:get/get.dart';

class LocalString extends Translations {

  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      // LOGIN PAGE
       'login_heading':'Login to your account',
      'email_hint':'Enter Email Address',
      'mobile_hint':'Enter Mobile Number',
      'login_button':'Login',
      'sub-text1':"Don't have an account?",
      'sub-text2':"Don't want to register?",
      'register':'REGISTER',
      'guest-login':'GUEST LOGIN',
      // REGISTRATION PAGE
      'registration_heading':'Register new account',
      'name_hint':'Enter Full Name',
      'Already_account':'Already have an account?',
      // OTP SCREEN
      'otp_heading':'OTP verification',
      'otp_content':'An OTP will be sent to your mobile number.\nPlease enter the number below.',
      'otp_sub_text':'Did not receive OTP? ',
      'otp_resend':'RESEND OTP',
      'login_caps':'LOGIN',
      // HOME SCREEN
      'home_heading1':'How can',
      'home_heading2':'help today?',
      'home_location':'Emaar Squre, Dubai',
      'home_search':'What are you looking for?',
      'home_content1':'Click on your preferred service and lets',
      'home_content2':'it',
      'home_ongoing':'Ongoing services',
      'home_emg_button':'Emergency Service',
      'home_emg_content1':'In case of an emergency service, our office assistant will get in touch with you to understand your requirement and take the process further. if you want to book an emergency service, please press the button below.',
      'home_emg_content1_button':'BOOK EMERGENCY SERVICE',
      'home_emg_content2':'We have received your emergency service request.Response time is less than 90 minutes.',
      'home_emg_content2_button':'GOT IT',
      'home_assist_button':'Need Assistance',
      'home_assist_content1':"Don't worry! We will help you out by getting in touch with you and understand your requirement. Click the button below to get assistance from us.",
      'home_assist_content2':'We understand that you need our assistance. We will get in touch with you shortly.',
      // BOTTOM BAR
      'HOME':'Home',
      'MY_BOOKINGS':'My Bookings',
      'MY_PROFILE':'My Profile',
      'BRANDS':'Brands',
      //DRAWER MENU
      'drawer_about':'About Us',
      'drawer_refer':'Refer & Earn',
      'drawer_rate':'Rate Us',
      'drawer_contact':'Contact Us',
      'drawer_privacy':'Privacy Policy',
      'drawer_conditions':'Terms & Conditions',
      'drawer_sign_out':'Sign Out',
      'refer_heading':'Refer & Earn',
      'refer_copy':'Copy',
      'refer_content':'Refer our app to your friends & family to\neanr a discount on our services!',
      'refer_sub_content':'You can also share the link for the app\nwith your friends and family.',
      'rate_app_heading':'Rate App',
      'rate_app_content':'Are you enjoying using our app?\nRate it!',
      'rate_app_feedback':'Enter your feedback here. Your suggestions help us\nimprove our services.',
      'rate_app_submit':'Submit',
      'contact_us_heading':'Contact Us',
      'contact_us_content':'if you have any questions about your booking,\nor any other queries, please let us know.',
      'contact_us_booking':'Do you have a service booking with us?',
      'contact_us_yes':'Yes',
      'contact_us_no':'No',
      'contact_us_desc':'Enter the description of your issue',
      'contact_us_textfield':'Please enter the description of the problem you are\nfacing. (Minimum 5 characters required)',
      //PROFILE SCREEN
      'profile_heading1':'Your Account',
      'profile_personal_info':'Personal information',
      'profile_payment':'Payment Cards',
      'profile_address':'Address',
      'profile_notifi':'Notification',
      'profile_heading2':'Support',
      'profile_touch':'Get in Touch',
      'profile_lang':'Language',
      'profile_Rate_app':'Rate the App',
      'personal_info':'Personal information',
      'address_title':'Address',
      'add_address':'Add New Address',
      'enable_notification_heading':'Enable All Notification',
      'enable_notification_sub':'Tap to recive all notification',
      'promos_offers':'Promos and Offers',
      'promos_offers_sub':'Tap to recive promotions and savings offers',
      'services_heading':'Services',
      'services_sub':'Tap to recive related to service updates',
      'notification_button':'SAVE CHANGES',
      'language_heading':'Select your preferred language',
      'language_sub':'Please select a language that you would like to\ncommunicate in',
      'language_button':'UPDATE',
      'rate_app':'Rate App',
      'rate_app_sub_text':'Are you enjoying using our app?\nRate it!',
      'rate_app_disc_text':'Enter your feedback here. Your suggestion help us\nimprove our service',
      'rate_button':'SUBMIT',
      //MAP SCREEN
      'confirm_address_button':'Confirm address',
           //_modalBottomSheetMenu
      'discription_of_problem':'Description of problem',
      'problem_hint':'Please enter the description of the problem you are facing.\n(Minimum 5 characters required)',
      'confirm_location_heading':'Confirm your Location',
      'proceed_button':'PROCEED',
      'image_video':'Upload image/video',
      'view_more':'View more',
      'select_date_time':'Select Date & Time',
      'date_time_button':'SELECT DATES',
      'point_of_contact':'Point of contact',
      'point_of_contact_button':'Add',

      'add_promo':'Add Promo',
      'promo_textfield':'Enter your promo code',
      'activate_code':'ACTIVATE CODE',
      'promo_sub_text':"Here's some promo codes",
      'apply_code':"Apply code",

      //ACTIVE BOOKING
      'cancel_heading':'Cancellation Policy',
      'cancel_heading_sub':'Before we proceed with the cancellation process, please\nmake sure to read cancellation policy',
      'details':'Details',
      'charge':'Charges',
      'cancel_sub_text1':'Cancel within 24 hours of \nconfirmation of service',
      'cancel_sub_text2':'Cancel after 24 hours of \nconfirmation of service',
      'refund':'Refund',
      'reschedule_heading':'Rescheduling Policy',
      'reschedule_heading_sub':'Before we proceed with the rescheduling process, please\nmake sure to read rescheduling policy',
      'reschedule_sub_text1':'Reschedule within 24 hours of \nconfirmation of service',
      'reschedule_sub_text2':'Reschedule after 24 hours of \nconfirmation of service',
      //MAP WITH ADDRESS SCREEN
      'map_with_address_button':'Enter complete address',
      'map_with_address_home':'Home',
      'map_with_address_office':'Office',
      'map_with_address_store':'Store',
      'map_with_address_other':'Other',
      'map_with_address_addAddress':'ADD ADDRESS',
      'map_with_address_flat':'Flat/Villa no',
      'map_with_address_building':'Building Name',
      'map_with_address_street':'Street Name',
      //PAYMENT SUMMARY SCREEN
     'payment_heading':'Payment Summary',
     'payment_name':'Full Name',
     'payment_email':'Email Address',
     'payment_mobile':'Mobile Number',
      'payment_service':'Service Type',
     'payment_visit':'Select Type of Visit',
     'payment_date':'Date and Time',
     'payment_description':'Description',
     'payment_address':'Address',
      'total':'Total',
      'grand_total':'Grand Total',
      'booking_success':'KEGI Booking successful',
      'back_to_home':'BACK TO HOME SCREEN',
           //_modalBottomSheetProceed
       'Select_visit_heading':'Select type of visit',
      'timesheet_heading':'Select Time',
       'Expert/specialist':'Expert/specialist visit required',
      'Expert/specialist_subtitle':'Supervisor will come to identify the issue.\nQuotation and timeline will be shared.',
      'per_hour':'per hour',
      'additional_hour':'Additional hours',
      'know_issue':"I know what's the issue",
      'know_issue_subtitle':"Quotation will be provided based on your\ndescription and photos.",
      'assistance_needed':"Assistance needed",
      'assistance_needed_subtitle':"We will call you and understand the\nrequirements.",
      'emergency_service':"Emergency service",
      'emergency_service_subtitle':"We will schedule the service on emergency\nbasis. Response time is less than 90 mins.",
      'surcharge':'surcharge',
      'Point_contact':'Point of contact',
      'Point_contact_subtitle':'You are not the point of contact? Check the box\nhere to add details of the new point of contact.',
      'cash_payment':'Cash Payment',
      'card_payment':'Card Payment',
      'discount':'Discount',
    },
    'ar_SA': {
      // LOGIN PAGE
      'login_heading':'تسجيل الدخول إلى حسابك',
      'email_hint':'أدخل عنوان البريد الالكتروني',
      'mobile_hint':'أدخل رقم الهاتف المتحرك',
      'login_button':'تسجيل الدخول',
      'sub-text1':"ليس لديك حساب؟",
      'sub-text2':"لا تريد التسجيل؟",
      'register':'تسجيل',
      'guest-login':'تسجيل دخول الزائر',
      // REGISTRATION PAGE
      'registration_heading':'تسجيل حساب جديد',
      'name_hint':'أدخل الاسم الكامل',
      'Already_account':'هل لديك حساب؟',
      // OTP SCREEN
      'otp_heading':'التحقق من OTP',
      'otp_content':'سيتم إرسال كلمة مرور لمرة\n واحدة إلى رقم هاتفك المحمول ، الرجاء إدخال الرقم أدناه.',
      'otp_sub_text':' لم تقم بإحياء OTP؟',
      'otp_resend':'إعادة إرسال OTP',
      'login_caps':'تسجيل الدخول',
      // HOME SCREEN
      'home_heading1':'كيف يمكن',
      'home_heading2':'مساعدة اليوم؟',
      'home_location':'ميدان إعمار ، دبي',
      'home_search':'ما الذي تبحث عنه؟',
      'home_content1':'انقر على الخدمة المفضلة لديك ويتيح لك ذلك',
      'home_content2':'هو - هي',
      'home_ongoing':'الخدمات الجارية',
      'home_emg_button':'خدمات الطوارئ',
      'home_emg_content1':'في حالة وجود خدمة طوارئ ، سيتواصل معك مساعد المكتب الخاص بنا لفهم متطلباتك والمضي قدمًا في العملية. إذا كنت ترغب في حجز خدمة الطوارئ ، يرجى الضغط على الزر أدناه.',
      'home_emg_content1_button':'احجز خدمة الطوارئ',
      'home_emg_content2':'لقد تلقينا طلب خدمة الطوارئ الخاص بك. وقت الاستجابة أقل من 90 دقيقة.',
      'home_emg_content2_button':'فهمتك',
      'home_assist_button':'احتاج مساعدة',
      'home_assist_content1':"لا تقلق! سنساعدك من خلال الاتصال بك وفهم متطلباتك. انقر فوق الزر أدناه للحصول على المساعدة منا.",
      'home_assist_content2':'نحن نتفهم أنك بحاجة إلى مساعدتنا. وسوف نحصل على اتصال معكم قريبا.',
      // BOTTOM BAR
      'HOME':'الصفحة الرئيسية',
      'MY_BOOKINGS':'حجوزاتي',
      'MY_PROFILE':'ملفي',
      'BRANDS':'العلامات التجارية',
      //DRAWER MENU
      'drawer_about':'معلومات عنا',
      'drawer_refer':'الإحالة وكسب',
      'drawer_rate':'قيمنا',
      'drawer_contact':'اتصل بنا',
      'drawer_privacy':'سياسة خاصة',
      'drawer_conditions':'البنود و الظروف',
      'drawer_sign_out':'خروج',
      'refer_heading':'الإحالة وكسب',
      'refer_copy':'ينسخ',
      'refer_content':'قم بإحالة تطبيقنا إلى أصدقائك وعائلتك \n للحصول على خصم على خدماتنا!',
      'refer_sub_content':'يمكنك أيضًا مشاركة رابط التطبيق \n مع أصدقائك وعائلتك.',
      'rate_app_heading':'قيم التطبيق',
      'rate_app_content':'هل تستمتع باستخدام تطبيقنا؟ \n قيّمه!',
      'rate_app_feedback':'أدخل ملاحظاتك هنا. تساعدنا اقتراحاتك \n في تحسين خدماتنا.',
      'rate_app_submit':'يقدم',
      'contact_us_heading':'اتصل بنا',
      'contact_us_content':'إذا كان لديك أي أسئلة حول حجزك \nو أي استفسارات أخرى ، فيرجى إخبارنا بذلك.',
      'contact_us_booking':'هل لديك خدمة الحجز معنا؟',
      'contact_us_yes':'نعم',
      'contact_us_no':'رقم',
      'contact_us_desc':'أدخل وصف مشكلتك',
      'contact_us_textfield':'الرجاء إدخال وصف المشكلة التي\n تواجهها. (الحد الأدنى المطلوب 5 أحرف)',
      //PROFILE SCREEN
      'profile_heading1':'الحساب الخاص بك',
      'profile_personal_info':'معلومات شخصية',
      'profile_payment':'بطاقات الدفع',
      'profile_address':'عنوان',
      'profile_notifi':'تنبيه',
      'profile_heading2':'الدعم',
      'profile_touch':'ابقى على تواصل',
      'profile_lang':'لغة',
      'profile_Rate_app':'قيم التطبيق',
      'personal_info':'معلومات شخصية',
      'address_title':'عنوان',
      'add_address':'أضف عنوان جديد',
      'enable_notification_heading':'تمكين كل التنبيهات',
      'enable_notification_sub':'انقر لتلقي كل الإشعارات',
      'promos_offers':'العروض الترويجية',
      'promos_offers_sub':'انقر لتلقي العروض الترويجية والتوفير',
      'services_heading':'خدمات',
      'services_sub':'انقر لتلقي تحديثات الخدمة ذات الصلة',
      'notification_button':'حفظ التغييرات',
      'language_heading':'اختر لغتك المفضلة',
      'language_sub':'الرجاء تحديد اللغة التي تريد \n التواصل بها',
      'language_button':'تحديث',
      'rate_app':'قيم التطبيق',
      'rate_app_sub_text':'هل تستمتع باستخدام تطبيقنا؟ \n قيّمه!',
      'rate_app_disc_text':'أدخل ملاحظاتك هنا. يساعدنا اقتراحك \n  في تحسين خدماتنا',
      'rate_button':'إرسال',
      //MAP SCREEN
      'confirm_address_button':'تأكيد العنوان',
         //_modalBottomSheetMenu
      'discription_of_problem':'وصف مشكلة',
      'problem_hint':'الرجاء إدخال وصف المشكلة التي تواجهها. \n (مطلوب 5 أحرف على الأقل)',
      'confirm_location_heading':'قم بتأكيد موقعك',
      'proceed_button':'تقدم',
      'image_video':'تحميل الصورة / الفيديو',
      'view_more':'عرض المزيد',
      'select_date_time':'حدد التاريخ والوقت',
      'date_time_button':'حدد التواريخ',
      'point_of_contact':'نقطة الاتصال',
      'point_of_contact_button':'يضيف',

      'add_promo':'إضافة ترويج',
      'promo_textfield':'إدخال الرمز الترويجي الخاص بك',
      'activate_code':'تفعيل القانون',
      'promo_sub_text':"إليك بعض الرموز الترويجية",
      'apply_code':"تطبيق الكود",

      //ACTIVE BOOKING
      'cancel_heading':'سياسة الإلغاء',
      'cancel_heading_sub':'قبل الشروع في عملية الإلغاء ، الرجاء \n التأكد من قراءة نهج الإلغاء',
      'details':'تفاصيل',
      'charge':'شحنة',
      'cancel_sub_text1':'قم بالإلغاء خلال 24 ساعة من \n تأكيد الخدمة',
      'cancel_sub_text2':'الإلغاء بعد 24 ساعة من \n تأكيد الخدمة',
      'reschedule_heading':'سياسة إعادة الجدولة',
      'reschedule_heading_sub':'قبل أن نواصل عملية إعادة الجدولة ، الرجاء \n  التأكد من قراءة نهج إعادة الجدولة',
      'reschedule_sub_text1':'أعد الجدولة خلال 24 ساعة من \ n تأكيد الخدمة',
      'reschedule_sub_text2':'إعادة الجدولة بعد 24 ساعة من \ n تأكيد الخدمة',

      //MAP WITH ADDRESS SCREEN
      'map_with_address_button':'أدخل العنوان الكامل',
      'map_with_address_home':'مسكن',
      'map_with_address_office':'مكتب. مقر. مركز',
      'map_with_address_store':'متجر',
      'map_with_address_other':'آخر',
      'map_with_address_addAddress':'اضف عنوان',
      'map_with_address_flat':'شقة / فيلا لا',
      'map_with_address_building':'اسم المبنى',
      'map_with_address_street':'اسم الشارع',
      //PAYMENT SUMMARY SCREEN
      'payment_heading':'ملخص الدفع',
      'payment_name':'الاسم الكامل',
      'payment_email':'عنوان بريد الكتروني',
      'payment_mobile':'رقم الهاتف المحمول',
      'payment_service':'نوع الخدمة',
      'payment_visit':'حدد نوع الزيارة',
      'payment_date':'التاريخ و الوقت',
      'payment_description':'وصف',
      'payment_address':'عنوان',
      'total':'المجموع',
      'grand_total':'المبلغ الإجمالي',
      'booking_success':'KEGI تم الحجز بنجاح',
      'back_to_home':'رجوع إلى شاشة الصفحة الرئيسية',
         //_modalBottomSheetProceed
      'Select_visit_heading':'حدد نوع الزيارة',
      'timesheet_heading':'حدد الوقت',
      'Expert/specialist':'مطلوب زيارة خبير / متخصص',
      'Expert/specialist_subtitle':'سيأتي المشرف للتعرف على المشكلة. \n ستتم مشاركة الاقتباس والمخطط الزمني.',
      'per_hour':'في الساعة',
      'additional_hour':'ساعات إضافية',
      'know_issue':"أعرف ما هي المشكلة",
      'know_issue_subtitle':"سيتم تقديم عرض الأسعار بناءً على \n وصفك وصورك",
      'assistance_needed':"المساعدة المطلوبة",
      'assistance_needed_subtitle':"سوف نتصل بك ونفهم \n المتطلبات.",
      'emergency_service':"خدمات الطوارئ",
      'emergency_service_subtitle':"سنقوم بجدولة الخدمة في قاعدة \n الطوارئ. وقت الاستجابة أقل من 90 دقيقة.",
      'surcharge':'تكلفة إضافية',
      'Point_contact':'نقطة الاتصال',
      'Point_contact_subtitle':'أنت لست نقطة الاتصال؟ حدد المربع \ n هنا لإضافة تفاصيل نقطة الاتصال الجديدة.',
      'cash_payment':'دفع نقدا',
      'card_payment':'بطاقه ائتمان',
      'discount':'خصم',
    },
  };
}